workspace:
  base: /srv/app
  path: src/code.gitea.io/git

clone:
  git:
    image: plugins/git:1
    # Tests require the entire history (for some reason)
    #depth: 50
    tags: true

pipeline:
  testing:
    image: webhippie/golang:edge
    pull: true
    commands:
      - git update-ref refs/heads/test HEAD
      - make clean
      - make vet
      - make lint
      - git --version
      - make test
      - curl "https://github.com/git/git/archive/v1.7.0.tar.gz"
      - mkdir build \
        && curl -fsSL "https://github.com/git/git/archive/v1.7.0.tar.gz" -o git.tar.gz \
        && tar -C build -xzf git.tar.gz \
        && cd build/git-1.7.0 \
        && chmod +x configure \
        && ./configure \
        && make all \
        && make install PREFIX=/usr/local \
        && cd ../.. \
        && rm -rf build \
        && rm git.tar.gz
      - git --version
      - hash -r
      - git --version
      - /usr/local/bin/git --version
      - make test
      - make build

  # coverage:
  #   image: plugins/coverage:1
  #   pull: true
  #   secrets: [ github_token ]
  #   server: https://coverage.gitea.io

  discord:
    image: appleboy/drone-discord:1.0.0
    pull: true
    secrets: [ discord_webhook_id, discord_webhook_token ]
    when:
      event: [ push, tag, pull_request ]
      status: [ changed, failure ]
